import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const bookings = sqliteTable('hotel_bookings', {
  id: text('id').primaryKey(),
  reference: text('reference').notNull().unique(),
  userId: text('user_id').notNull(),
  requestKey: text('request_key').notNull(),
  requestHash: text('request_hash').notNull(),
  roomType: text('room_type').notNull(),
  roomNumber: integer('room_number').notNull(),
  checkIn: text('check_in').notNull(),
  checkOut: text('check_out').notNull(),
  guests: integer('guests').notNull(),
  guestName: text('guest_name').notNull(),
  guestEmail: text('guest_email').notNull(),
  guestPhone: text('guest_phone').notNull(),
  requests: text('requests').notNull().default(''),
  breakfast: integer('breakfast').notNull().default(0),
  nightlyPrice: integer('nightly_price').notNull(),
  nights: integer('nights').notNull(),
  total: integer('total').notNull(),
  status: text('status').notNull().default('confirmed'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
}, t => [
  uniqueIndex('hotel_bookings_request_key').on(t.userId,t.requestKey),
  index('hotel_bookings_user_created').on(t.userId,t.createdAt),
  index('hotel_bookings_room_dates').on(t.roomType,t.roomNumber,t.status,t.checkIn,t.checkOut),
  index('hotel_bookings_status_arrival').on(t.status,t.checkIn),
]);
